### ISSUE TITLE
Issues en usuario: Estudiante

### ISSUE THREAD

**Issue by AlejandroBC1007** [EliasEsperanza/Proyeccion-Social#278]
1- En la vista ‘’Documentos’’ se interrumpen y bloquean las descargas de los archivos ‘’Informe del 50% del Servicio Social’’ e ‘’Informe del 100% del Servicio Social’’
![Captura de pantalla 2024-11-23 165835](https://github.com/user-attachments/assets/34286914-eb6f-4ebf-92c0-26cceb6dafa9)

2- Botón de notificaciones sigue sin estar funcional

**Comment by 0kev0** [comment]
funciona 
![image_2024-11-23_230256605](https://github.com/user-attachments/assets/e099f875-9731-45d1-8074-8a7f615ccacf)
