### ISSUE TITLE
Error al mostrar el rol en la vista "Usuarios" desde el rol de Admin 

### ISSUE THREAD

**Issue by RaquelVentura** [EliasEsperanza/Proyeccion-Social#280]
1.A todos los usuarios les sale en rol "administrador", aunque tengan otro rol asignado 

![Captura desde 2024-11-23 18-20-48](https://github.com/user-attachments/assets/eb7549d0-3b81-4029-a2f8-cec42af61741)

**Comment by 0kev0** [comment]
resuelto
