### ISSUE TITLE
Issues vista Proyectos disponibles:Admin

### ISSUE THREAD

**Issue by AntolinoRetana** [EliasEsperanza/Proyeccion-Social#281]
En la vista proyectos disponibles, al darle click al boton de editar
![image](https://github.com/user-attachments/assets/00c93264-9f15-4723-93a0-5dd0693a4012)

deberia de mostrar la vista que se llama editar-proyecto.blade.php
pero muestra esta vista
![image](https://github.com/user-attachments/assets/aeaab7bd-df63-4b3a-ab71-e2f37d0ffa0a)

Y esta vista no es la de editar proyectos de la vista proyectos disponibles.

**Comment by R0bert09** [comment]
ya se soluciono esta falla
