### ISSUE TITLE
Fallo en la vistar publicar proyecto

### ISSUE THREAD

**Issue by yoselinuesfom** [EliasEsperanza/Proyeccion-Social#283]
![Captura de pantalla 2024-11-23 184239](https://github.com/user-attachments/assets/303becfc-195a-458e-92c8-6f0cdb8db0d0)

no deja publicar proyecto por que no parece la sección

**Comment by 0kev0** [comment]
hasta que un admin asigna seccion  a un coordinador podra publicar proyecto
