### ISSUE TITLE
Error al eliminar elementos, en la vista "proyectos disponibles" de admin

### ISSUE THREAD

**Issue by RaquelVentura** [EliasEsperanza/Proyeccion-Social#289]
Al darle click al icono de eliminar , lanza error 404, en la vista de **proyectos disponibles**
![image](https://github.com/user-attachments/assets/7e5841dd-428f-4e09-811b-b0c784d09ae7)

![image](https://github.com/user-attachments/assets/18befa70-d0e7-44c3-9df2-1c0776bbeb3f)

**Comment by R0bert09** [comment]
issue solucionado
