### ISSUE TITLE
Error de filtro por rol, en la vista "Usuarios"  en las vistas de Admin

### ISSUE THREAD

**Issue by RaquelVentura** [EliasEsperanza/Proyeccion-Social#291]
Al selccionar cualquier rol, sea estudiante, coordinador, admin, o tutor, da error
![image](https://github.com/user-attachments/assets/544f7cfb-de1c-4a5c-b87a-bf2f557acbd5)
![image](https://github.com/user-attachments/assets/37f888a2-69c9-46dd-833d-87a452b30b54)

**Comment by R0bert09** [comment]
Problema solucionado por Eliseo Santos
