### ISSUE TITLE
Validacion sanitisar input y middleware actualizar password de usuario

### ISSUE THREAD

**Issue by 0kev0** [EliasEsperanza/Proyeccion-Social#362]
- DEBE MOSTRAR RETROALIMENTACION EN TODOS LOS CASOS y verificar con los middlewares 

blade editar usuario y actualizar password
![image](https://github.com/user-attachments/assets/e6d9c9ff-2db4-4b4a-ac61-964f742051e2)

![image](https://github.com/user-attachments/assets/1d7ef79b-8b25-4a70-bf32-af53a97882a8)

**Comment by Lovoh17** [comment]
ya estan validados con el midlewere glabal
