### ISSUE TITLE
Validar y sanitisar datos de form Asignar Proyecto con middleware 

### ISSUE THREAD

**Issue by 0kev0** [EliasEsperanza/Proyeccion-Social#365]
- DEBE MOSTRAR RETROALIMENTACION EN TODOS LOS CASOS y verificar con los middlewares 

- Sanitisar los input ingresados y evitar errores/ataques (json malisioso, inyección sql etc)

en blade GestiónProyectos

![image](https://github.com/user-attachments/assets/aae3fa7c-d11b-49d7-bb0c-9d305c5c03b1)

**Comment by Lovoh17** [comment]
ya estan validados con el midlewere global
