### ISSUE TITLE
Validar inputs delform 'solicitud de Proyecto' con middleware 

### ISSUE THREAD

**Issue by 0kev0** [EliasEsperanza/Proyeccion-Social#367]
- DEBE MOSTRAR RETROALIMENTACION EN TODOS LOS CASOS y verificar con los middlewares 

- Sanitisar los input ingresados y evitar errores/ataques (json malisioso, inyección sql etc)

En blade solicitud-Proyecto

![image](https://github.com/user-attachments/assets/7c4aa86e-ba9f-4a10-8686-9394c0917d6a)

**Comment by Lovoh17** [comment]
ya estan validados con el midlewere glabal
